# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jaume Sala - Software Engineer and much more.
email: jaumesala@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal website. Software Engineer by voation.
  Front End Web Developer, UX Engineer, Smart Cities Expert.
  Music, Movies, Travel, Knowledge in general.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jaumesala.net" # the base hostname & protocol for your site

github_username:  jaumesala
linkedin_username: jaumesala
twitter_username: jaumesala84

exclude: ['node_modules', 'vendor', 'resources', 'bower.json', 'gulpfile.js', 'package.json', 'npm-debug.log']
include: []

# Build settings
markdown: kramdown

timezone: Europe/Madrid
google_analytics: UA-XXXXX-X


controller: page
method: index